### ISSUE TITLE
A ListView cellák színe narancs ha rákattintasz >:(

### ISSUE THREAD

**Issue by Rettend** [14A-A-Lyedlik-Devs/friendli-or-angri#18]

**Comment by Sylvester2003** [comment]
Ez megoldhatatlan, mivel a maui egy FOSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS!
