### ISSUE TITLE
Név bekérése

### ISSUE THREAD

**Issue by MAttila42** [14A-A-Lyedlik-Devs/friendli-or-angri#32]
A program elindításakor, ha nem volt még megadva, akkor kérjen be egy felhasználónevet, amit sqlite-ban tároljon el a telefon. Valahol akár meg is jelenhet, főoldalon, statisztikában, akármi. Utána ne lehessen módosítani.

Ha lesz backend és rendes leaderboard, akkor majd ezzel a névvel fognak megjelenni.

**Comment by Rettend** [comment]
Good call @ExAtom!

**Comment by MAttila42** [comment]
Még annyi, hogy olyan designesen jelenjen meg, hogy **Név**_#69_. Itt annyira nem látszik, de legyen a szám mindig mellé fűzve, de ne annyira feltűnően, kicsit halványan, kisebb betűvel netán.

**Comment by MAttila42** [comment]
Mikor az app elindul, legyen ellenőrízve, hogy van-e az sqliteba már tárolva név, id és token.

Ha nincs név, id vagy token, akkor egy felugró ablakban kérjünk be egy nevet. A nevet elküldjük a backendnek (POST `http://localhost:5124/api/Users?userName=<user neve>`). Visszakapunk egy user objektumot, amiben már minden benne van (név, id, token), és ezt tároljuk is el.

Ha mind a három érték ki van töltve, akkor nem kell felugró ablak (de mondjuk ellenőrízni lehetne azzal, hogy elküldjük a szervernek a tokent, amiből visszakapjuk a felhasználónevet és az id-t, nehogy hibás legyen (GET `http://localhost:5124/api/Users?token=<token>`). Illetve ha hibás a token, akkor meg kérjünk be nevet)
